export const items: { [key: string]: string[] } = {
	repair: ['Tamir'],
	engine: ['default', 'STAGE 1', 'STAGE 2', 'STAGE 3', 'STAGE 4'],
	transmission: ['default', 'Sokak', 'Spor', 'Yarış'],
	brakes: ['default', 'Sokak', 'Spor', 'Yarış'],
	turbo: ['default', 'Turbo-kiti'],
	suspension: ['default', 'Alçaltılmış', 'Sokak', 'Spor', 'Yarış'],
	armor: ['default', '20%', '40%', '60%', '80%', '100%'],
	engine_sound: [
		'6.0L V8',
		'3.0L I6',
		'5.2L V10',
		'2.6L I6',
		'1.3L Twin-Rotor',
		'5.8L Twin-Charged V8',
		'7.3L V12',
		'6.0L V12',
		'2.0L I4',
		'4.0L Flat-6',
		'5.2L V8'
	],
	horn: [
		'default',
		'Kamyon',
		'Polis',
		'Palyaço',
		'Müzikal 1',
		'Müzikal 2',
		'Müzikal 3',
		'Müzikal 4',
		'Müzikal 5',
		'Üzgün trompet',
		'Klasik 1',
		'Klasik 2',
		'Klasik 3',
		'Klasik 4',
		'Klasik 5',
		'Klasik 6',
		'Klasik 7',
		'Nota - Do',
		'Nota - Re',
		'Nota - Mi',
		'Nota - Fa',
		'Nota - Sol',
		'Nota - La',
		'Nota - Si',
		'Nota - Do (yüksek)',
		'Caz 1',
		'Caz 2',
		'Caz 3',
		'Caz (tekrar)'
	],
	tint: ['default', 'Saf siyah', 'Koyu duman', 'Açık duman', 'Limo', 'Yeşil'],
	lights: [
		'default',
		'Beyaz',
		'Mavi',
		'Açık mavi',
		'Yeşil',
		'Açık yeşil',
		'Açık sarı',
		'Sarı',
		'Turuncu',
		'Kırmızı',
		'Pembe',
		'Mor',
		'Açık mor'
	],
	neon: ['default', 'Tak'],
	plate: [
		'default',
		'Siyah üstüne sarı',
		'Mavi üstüne sarı',
		'Beyaz üstüne mavi #2',
		'Beyaz üstüne mavi #3',
		'Beyaz üstüne siyah'
	],
	paint: ['Ana renk', 'Ek renk', 'Jant rengi', 'Lastik dumanı'],
	rims: [],
	spoiler: [],
	sideskirt: [],
	exhaust: [],
	hood: [],
	roof: [],
	frame: [],
	grille: [],
	livery: [],
	front_bumper: [],
	rear_bumper: []
};
